# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8304781584f32028a87de5aeeef18c0bc9172719c884df174ef7768327394ec39bb0d738a6cb1990a1062165ebcb241e5f90809303c916719f144ac52bdceb80

test:
  secret_key_base: 68ab0179c42897062eb10145ced2983120b3b6dba218fc1098605736fdf88a6ca745266eb229b7ae7db5fe267d52c00e750d63fee7bf9fea8ef457b8ab2b1bde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: config.secret_key = '1b73180fd90dfac8cd32ca00dda1ce22c81f65f1ddaef602902ef52dfb35e4a86c2b8911182509154d47dd8458eea95cde42ad89dd34637f5e1179dcef294764'
